default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: trecker_t_development

test:
  <<: *default
  database: trecker_t_test

production:
  <<: *default
  database: trecker_t_production
  username: trecker
  password: password

